cms/urls.py
from django.conf.urls import url
from django.urls import path
from .views import ViewHome, ViewAbout, ViewEinkaufsliste, ViewEinkaufdetail, ViewEinkaufinsert, ViewSenderliste, ViewSenderdetail, ViewSenderdelete, ViewSenderinsert, ViewEinkaufdelete

app_name = 'cms'

urlpatterns = [
  path('', ViewHome, name='home'),
  path('about/', ViewAbout, name='about'),
  path('einkaufsliste/', ViewEinkaufsliste, name='einkaufsliste'),
  path('einkaufdetail/', ViewEinkaufinsert, name='einkaufdetail'),
  path('einkaufdelete/<int:einkauf_id>', ViewEinkaufdelete, name='einkaufdelete'),
  path('einkaufdetail/<int:einkauf_id>/', ViewEinkaufdetail, name='einkaufdetail'),
  path('senderliste/', ViewSenderliste, name='senderliste'),
  path('senderdetail/', ViewSenderinsert, name='senderdetail'),
  path('senderdelete/<int:sender_id>', ViewSenderdelete, name='senderdelete'),
  path('senderdetail/<int:sender_id>/', ViewSenderdetail, name='senderdetail'),
]

settings/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('cms.urls', namespace='cms')),
]

cms/models.py
import json
from django.db import models

class EinkaufslisteModel(models.Model):
    title = models.CharField('Title', max_length=200, blank=False)	
    price = models.DecimalField('price',max_digits=7, decimal_places=2, default=0.00)

    def __str__(self):
        return self.title
        
class SenderlisteModel(models.Model):        
    nr = models.CharField('nr', max_length=20, blank=False, default='000')	
    title = models.CharField('Title', max_length=200, blank=False)	
    link = models.CharField('Link', max_length=200, blank=False)	

    def __str__(self):
        return self.title

#    def save(self, commit=True):
#        return super(SenderlisteModel, self).save(commit)        

class AboutModel(models.Model):
    with open("version.json", "r") as read_file:
      data = json.load(read_file)
      versnr=data["versnr"]	
      versdat=data["versdat"]

customized_sitetree_models = False

if customized_sitetree_models:

    from sitetree.models import TreeItemBase, TreeBase


    class MyTree(TreeBase):

        custom_field = models.CharField('Custom tree field', max_length=50, null=True, blank=True)


    class MyTreeItem(TreeItemBase):

        custom_field = models.IntegerField('Custom item field', default=42)

cms/views.py
from __future__ import unicode_literals
from django.shortcuts import render, get_list_or_404, redirect, get_object_or_404
from sitetree.toolbox import register_i18n_trees
from .utils import render_themed
from .models import AboutModel, EinkaufslisteModel, SenderlisteModel


register_i18n_trees(['main'])

def ViewHome(request):
    return render_themed(request, 'home', {})
    
def ViewAbout(request):
    context={
        'versnr':AboutModel.versnr,
        'versdat':AboutModel.versdat}	
    return render_themed(request, 'about', context)	
    	
def ViewEinkaufsliste(request):
    einkaufid = request.POST.get('einkaufid', None)
    if 'loeschen' in request.POST:
        EinkaufslisteModel.objects.filter(pk=einkaufid).delete()
    if 'speichern' in request.POST:
        title = request.POST.get('title', '')
        neu = request.POST.get('neu', 'N')
        if neu=="J":
            einkauf=EinkaufslisteModel.objects.create(title=title)
        else:        	    		
            einkauf=EinkaufslisteModel(id=einkaufid,title=title)
        einkauf.save()
    return render_themed(request, 'einkaufsliste', {'einkaufsliste': get_list_or_404(EinkaufslisteModel)})

def ViewEinkaufdetail(request, einkauf_id=0):
    einkauf = get_object_or_404(EinkaufslisteModel,id=einkauf_id)	
    return render_themed(request, 'einkaufdetail', {'einkauf':einkauf})

def ViewEinkaufinsert(request):
    return render_themed(request, 'einkaufdetail', {})

def ViewEinkaufdelete(request, einkauf_id=0):
    einkauf = get_object_or_404(EinkaufslisteModel,id=einkauf_id)	
    return render_themed(request, 'einkaufdelete', {'einkauf':einkauf})


def ViewSenderliste(request):
    senderid = request.POST.get('senderid', 0)    		
    if 'loeschen' in request.POST:
        SenderlisteModel.objects.filter(pk=senderid).delete()
    if 'speichern' in request.POST:
        nr = request.POST.get('nr', '')    		
        title = request.POST.get('title', '')    		
        link = request.POST.get('link', '')
        neu = request.POST.get('neu', 'N')
        if neu=="J":
            sender=SenderlisteModel.objects.create(nr=nr,title=title,link=link)
        else:        	    		
            sender=SenderlisteModel(id=senderid,nr=nr,title=title,link=link)
        sender.save()
    return render_themed(request, 'senderliste', {'senderliste': get_list_or_404(SenderlisteModel.objects.order_by('nr'))})
    
def ViewSenderdetail(request, sender_id=0):
    sender = get_object_or_404(SenderlisteModel,id=sender_id)	
    return render_themed(request, 'senderdetail', {'sender':sender})

def ViewSenderinsert(request):
    return render_themed(request, 'senderdetail', {})

def ViewSenderdelete(request, sender_id=0):
    sender = get_object_or_404(SenderlisteModel,id=sender_id)	
    return render_themed(request, 'senderdelete', {'sender':sender})
    

cms/templates/about.html
{% extends '1base.html' %}
{% load sitetree %}


{% block body %}
    {% include tpl_body %}
{% endblock %}

cms/templates/about_contents.html
{% load sitetree %}

<div id="page-contents">
    <h1>{% sitetree_page_title from "main" %} </h1>

    <table>
    <tr><td>Stand </td><td>: {{versdat|default:"01.01.1970"}}</td></tr>
    <tr><td>Version </td><td>: {{versnr|default:"0.x"}}</td></tr>
    </table>
    
</div>

cms/templates/einkauf_contents.html
{% load sitetree %}

<div id="page-contents">
    <h1>{% sitetree_page_title from "main" %} </h1>
Einkauf
</div>

cms/templates/einkauf_none.html
{%  load sitetree %}

<div class="container">
    <legend>Joorgpython</legend>
    <div class="navbar navbar-expand-lg navbar-dark bg-dark">
        {% sitetree_menu from "main" include "trunk" template "sitetree/menu_bootstrap4.html" %}
    </div>

    <div class="row mt-3">
        <div class="col-md-3">
            {% sitetree_menu from "main" include "this-siblings" template "sitetree/menu_bootstrap4_navpills-stacked.html" %}
        </div>
        <div class="col-md-9">
            {% sitetree_breadcrumbs from "main" template "sitetree/breadcrumbs_bootstrap4.html" %}

            {% include 'einkauf_contents.html' %}
        </div>
    </div>

</div>

cms/templates/einkaufdelete.html
{% extends '1base.html' %}
{% load sitetree %}


{% block body %}
    {% include tpl_body %}
{% endblock %}

cms/templates/einkaufsliste.html
{% extends '1base.html' %}
{% load sitetree %}


{% block body %}
    {% include tpl_body %}
{% endblock %}

cms/templates/einkaufsliste_none.html
{%  load sitetree %}

<div class="container">
    <legend>Joorgpython</legend>
    <div class="navbar navbar-expand-lg navbar-dark bg-dark">
        {% sitetree_menu from "main" include "trunk" template "sitetree/menu_bootstrap4.html" %}
    </div>

    <div class="row mt-3">
        <div class="col-md-3">
            {% sitetree_menu from "main" include "this-siblings" template "sitetree/menu_bootstrap4_navpills-stacked.html" %}
        </div>
        <div class="col-md-9">
            {% sitetree_breadcrumbs from "main" template "sitetree/breadcrumbs_bootstrap4.html" %}

            {% include 'einkaufsliste_contents.html' %}
        </div>
    </div>

</div>

cms/templates/home.html
{% extends '1base.html' %}
{% load sitetree %}

{% block body %}
    {% include tpl_body %}
{% endblock %}

cms/templates/home_contents.html
{% load sitetree %}

<div id="page-contents">
    <h1>{% sitetree_page_title from "main" %} </h1>

    <h2>Willkommen auf der Seite von Horst Meyer!</h2>    
</div>

cms/templates/senderdelete.html
{% extends '1base.html' %}
{% load sitetree %}


{% block body %}
    {% include tpl_body %}
{% endblock %}

cms/templates/senderdelete_none.html
{%  load sitetree %}

<div class="container">
    <legend>Joorgpython</legend>
    <div class="navbar navbar-expand-lg navbar-dark bg-dark">
        {% sitetree_menu from "main" include "trunk" template "sitetree/menu_bootstrap4.html" %}
    </div>
    <a href="{% url 'cms:senderliste' %}" class='btn btn-primary btn-sm active' role='button'>Zurück</a>
    <form class='form-horizontal' method='post' action='{% url "cms:senderliste" %}' role='form'>
      <div class="alert alert-warning" role="alert">
      Datensatz '{{ sender.title }}' wirklich löschen?
      </div>      
      {% csrf_token %}
      <input type="hidden" name="senderid" value="{{ sender.id }}"/>
      <input type="hidden" name="loeschen" value="1"/>
      <input type='submit' value='Löschen' />
   </form>
</div>

cms/templates/senderdetail_none.html
{%  load sitetree %}

<div class="container">
    <legend>Joorgpython</legend>
    <div class="navbar navbar-expand-lg navbar-dark bg-dark">
        {% sitetree_menu from "main" include "trunk" template "sitetree/menu_bootstrap4.html" %}
    </div>
    <a href="{% url 'cms:senderliste' %}" class='btn btn-primary btn-sm active' role='button'>Zurück</a>
    <form class='form-horizontal' method='post' action='{% url "cms:senderliste" %}' role='form'>
      <div class='table-responsive'>
      <table class='table'>
      <tr>
      <td class='col-md-1'><label>ID:</label></td>
      <td class='col-md-2'>{{ sender.id }}</td>
      </tr>
      <tr>
      <td class='col-md-1'><label>Nr:</label></td>
      <td class='col-md-2'><input type='text' name='nr' value='{{ sender.nr }}'/></td>
      </tr>
      <tr>
      <td class='col-md-1'><label>Sender:</label></td>
      <td class='col-md-2'><input type='text' name='title' value='{{ sender.title }}'/></td>
      </tr>
      <tr>
      <td class='col-md-1'><label>Link:</label></td>
      <td class='col-md-2'><input type='text' name='link' value='{{ sender.link }}'/></td>
      </tr>
      </table>
      </div>
      {% csrf_token %}
      {% if sender.id == None %}
        <input type="hidden" name="neu" value="J" />
        <input type="hidden" name="senderid" value="999" />
      {% else %}
        <input type="hidden" name="neu" value="N" />
        <input type="hidden" name="senderid" value="{{ sender.id }}"/>
      {% endif %}
      <input type="hidden" name="speichern" value="1"/>
      <input type='submit' value='Speichern' />
   </form>
</div>

cms/templates/senderinsert.html
<html>
Sender Insert
</html>

cms/templates/senderliste.html
{% extends '1base.html' %}
{% load sitetree %}


{% block body %}
    {% include tpl_body %}
{% endblock %}